Managed kafka example
jboss-fuse/camel-quarkus-examples pull request #9
Opened 2021-10-21 15:52 UTC by zbendhiba

this PR ENTESB-17658 & ENTESB-17657

2021-10-25 13:14 UTC, ppalaga requested changes
Except for the comment inline:

I see that these changes are product specific. But still, I wonder how we can ensure to have these changes in next product releases. Is there no way to have this content in the upstream? - that would be safest. Otherwise we should at least document the changes somewhere, e.g. in [CQ product/README.adoc](https://github.com/jboss-fuse/camel-quarkus/blob/camel-quarkus-2.2.0-product/product/README.adoc), WDYT?

2021-10-25 13:14 UTC, ppalaga commented on kafka/pom.xml
>          <camel-quarkus.platform.artifact-id>quarkus-camel-bom</camel-quarkus.platform.artifact-id>
I doubt this can work. there is no `quarkus.io:quarkus-camel-bom`. It should be either `com.redhat.quarkus.platform:quarkus-camel-bom` (preferred, no change) or `org.apache.camel.quarkus:camel-quarkus-bom` (for local testing).

Same for ` <camel-quarkus.platform.version>2.2.0.fuse-800019-redhat-00001</camel-quarkus.platform.version>` above. It would be better to avoid that change. To test locally, you can pass these props via `-D`

2021-10-26 08:48 UTC, zbendhiba commented
@ppalaga Let's discuss this difference between upstream and downstream later.
Maybe a good deal would be to name it not kafka, but managed kafka example. As the Readme is completely different.

2021-10-26 09:36 UTC, ppalaga commented
> @ppalaga Let's discuss this difference between upstream and downstream later. Maybe a good deal would be to name it not kafka, but managed kafka example. As the Readme is completely different.

+1, created https://issues.redhat.com/browse/ENTESB-17695 for the next release.

Let me fix the `<camel-quarkus.platform.group-id>` & Co.

2021-10-26 09:50 UTC, merged

2021-10-26 09:50 UTC, ppalaga commented
Thanks @zbendhiba !